 2019-10-28 10:22:14,207 [P4036/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.10.5 application starting on LAPTOP-OH8RPRRH
 2019-10-28 10:22:14,234 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2019-10-28 10:22:14,252 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 17ms)
 2019-10-28 10:22:14,303 [P4036/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2019-10-28 10:22:14,304 [P4036/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2019-10-28 10:22:14,306 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:22:15,157 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 851ms)
 2019-10-28 10:22:15,158 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2019-10-28 10:22:15,159 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 0ms)
 2019-10-28 10:22:15,225 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:22:15,225 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:22:15,226 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2019-10-28 10:22:15,226 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2019-10-28 10:22:15,226 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:22:15,226 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:22:15,227 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2019-10-28 10:22:15,228 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 1ms)
 2019-10-28 10:22:15,238 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:22:15,239 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:22:15,239 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2019-10-28 10:22:15,239 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 0ms)
 2019-10-28 10:22:15,240 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:22:15,240 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:22:15,240 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2019-10-28 10:22:15,240 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 0ms)
 2019-10-28 10:22:17,762 [P4036/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2019-10-28 10:22:18,463 [P4036/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2019-10-28 10:22:18,672 [P4036/D2/T1] WARN  Umbraco.Core.Sync.DatabaseServerMessenger - No last synced Id found, this generally means this is a new server/install. The server will build its caches and indexes, and then adjust its last synced Id to the latest found in the database and maintain cache updates based on that Id.
 2019-10-28 10:22:18,975 [P4036/D2/T1] INFO  umbraco.content - Load Xml from file...
 2019-10-28 10:22:18,987 [P4036/D2/T1] INFO  umbraco.content - Loaded Xml from file.
 2019-10-28 10:22:18,991 [P4036/D2/T1] INFO  umbraco.content - Loading content from database...
 2019-10-28 10:22:20,666 [P4036/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalIndexSet to be unlocked since it was left in a locked state
 2019-10-28 10:22:20,668 [P4036/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index ExternalIndexSet to be unlocked since it was left in a locked state
 2019-10-28 10:22:20,670 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=InternalMemberIndexer, NodeId=-1
 2019-10-28 10:22:20,725 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - member, Provider=InternalMemberIndexer, NodeId=-1
 2019-10-28 10:22:21,924 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - member, took 1198ms, Provider=InternalMemberIndexer, NodeId=-1
 2019-10-28 10:22:21,925 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=InternalIndexer, NodeId=-1
 2019-10-28 10:22:21,944 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - content, Provider=InternalIndexer, NodeId=-1
 2019-10-28 10:22:24,439 [P4036/D2/T15] INFO  umbraco.content - Save Xml to file...
 2019-10-28 10:22:24,448 [P4036/D2/T15] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 10:22:24,772 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:22:24,773 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:22:24,773 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2019-10-28 10:22:24,774 [P4036/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 0ms)
 2019-10-28 10:22:25,113 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - content, took 3168ms, Provider=InternalIndexer, NodeId=-1
 2019-10-28 10:22:25,114 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - media, Provider=InternalIndexer, NodeId=-1
 2019-10-28 10:22:26,211 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - media, took 1097ms, Provider=InternalIndexer, NodeId=-1
 2019-10-28 10:22:26,211 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=ExternalIndexer, NodeId=-1
 2019-10-28 10:22:26,220 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - content, Provider=ExternalIndexer, NodeId=-1
 2019-10-28 10:22:27,435 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - content, took 1213ms, Provider=ExternalIndexer, NodeId=-1
 2019-10-28 10:22:27,435 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - media, Provider=ExternalIndexer, NodeId=-1
 2019-10-28 10:22:28,141 [P4036/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - media, took 705ms, Provider=ExternalIndexer, NodeId=-1
 2019-10-28 10:22:28,147 [P4036/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2019-10-28 10:22:28,148 [P4036/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2019-10-28 10:22:28,162 [P4036/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 14087ms)
 2019-10-28 10:22:30,761 [P4036/D2/T11] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost/umbraco
 2019-10-28 10:22:30,762 [P4036/D2/T11] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost/umbraco (UmbracoModule request)
 2019-10-28 10:23:06,196 [P4036/D2/T13] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:23:06,197 [P4036/D2/T13] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:23:06,197 [P4036/D2/T13] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2019-10-28 10:23:06,198 [P4036/D2/T13] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2019-10-28 10:23:06,312 [P4036/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:23:06,312 [P4036/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:23:06,312 [P4036/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2019-10-28 10:23:06,313 [P4036/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 0ms)
 2019-10-28 10:23:20,392 [P4036/D2/T13] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:23:20,392 [P4036/D2/T13] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:23:20,393 [P4036/D2/T13] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2019-10-28 10:23:20,393 [P4036/D2/T13] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 0ms)
 2019-10-28 10:23:26,208 [P4036/D2/T13] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt failed for username joakiimm@hotmail.com from IP address ::1
 2019-10-28 10:23:31,154 [P4036/D2/T19] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:23:31,154 [P4036/D2/T19] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:23:31,154 [P4036/D2/T19] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2019-10-28 10:23:31,155 [P4036/D2/T19] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 0ms)
 2019-10-28 10:23:31,382 [P4036/D2/T13] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2019-10-27 10:23:31
 2019-10-28 10:23:35,505 [P4036/D2/T8] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 10:23:43,646 [P4036/D2/T13] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt failed for username joakiimm@hotmail.com from IP address ::1
 2019-10-28 10:24:14,445 [P4036/D2/T23] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username w.tamim@hotmail.com from IP address ::1
 2019-10-28 10:24:14,445 [P4036/D2/T23] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: w.tamim@hotmail.com logged in from IP address ::1
 2019-10-28 10:24:18,118 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:24:18,118 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:24:18,118 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2019-10-28 10:24:18,119 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 0ms)
 2019-10-28 10:24:18,130 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:24:18,130 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:24:18,131 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2019-10-28 10:24:18,131 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2019-10-28 10:24:18,133 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:24:18,134 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:24:18,134 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2019-10-28 10:24:18,134 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 0ms)
 2019-10-28 10:24:18,155 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:24:18,156 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:24:18,156 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2019-10-28 10:24:18,156 [P4036/D2/T25] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 0ms)
 2019-10-28 10:25:06,400 [P4036/D2/T13] INFO  Umbraco.Web.Editors.AuthenticationController - User w.tamim@hotmail.com from IP address ::1 has logged out
 2019-10-28 10:25:28,235 [P4036/D2/T9] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username joakiimm@hotmail.com from IP address ::1
 2019-10-28 10:25:28,236 [P4036/D2/T9] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: joakiimm@hotmail.com logged in from IP address ::1
 2019-10-28 10:27:21,688 [P4036/D2/T9] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Denmark' with Id '0' has been published.
 2019-10-28 10:27:27,682 [P4036/D2/T9] INFO  umbraco.content - Save Xml to file...
 2019-10-28 10:27:27,692 [P4036/D2/T9] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 10:27:45,181 [P4036/D2/T36] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'France' with Id '0' has been published.
 2019-10-28 10:27:51,010 [P4036/D2/T36] INFO  umbraco.content - Save Xml to file...
 2019-10-28 10:27:51,021 [P4036/D2/T36] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 10:28:39,519 [P4036/D2/T30] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 10:29:45,282 [P4036/D2/T28] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Corporate Headquarters' with Id '1066' has been published.
 2019-10-28 10:29:51,155 [P4036/D2/T35] INFO  umbraco.content - Save Xml to file...
 2019-10-28 10:29:51,165 [P4036/D2/T35] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 10:30:00,253 [P4036/D2/T7] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Corporate Headquarters' with Id '1066' has been published.
 2019-10-28 10:30:06,151 [P4036/D2/T7] INFO  umbraco.content - Save Xml to file...
 2019-10-28 10:30:06,161 [P4036/D2/T7] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 10:33:36,172 [P4036/D2/T13] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:33:40,728 [P4036/D2/T9] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:33:43,535 [P4036/D2/T44] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 10:33:44,465 [P4036/D2/T46] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:34:10,175 [P4036/D2/T41] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:34:17,827 [P4036/D2/T41] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:34:44,929 [P4036/D2/T38] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:34:46,532 [P4036/D2/T43] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:34:51,244 [P4036/D2/T46] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:34:54,128 [P4036/D2/T41] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:35:18,304 [P4036/D2/T18] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:35:23,346 [P4036/D2/T20] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:37:57,363 [P4036/D2/T54] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 10:37:57,364 [P4036/D2/T54] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 10:37:57,364 [P4036/D2/T54] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Editors.IEditorValidator
 2019-10-28 10:37:57,376 [P4036/D2/T54] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Editors.IEditorValidator (took 11ms)
 2019-10-28 10:38:25,689 [P4036/D2/T49] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:38:47,558 [P4036/D2/T62] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 10:39:43,561 [P4036/D2/T58] INFO  umbraco.content - Loading content from database...
 2019-10-28 10:39:48,308 [P4036/D2/T69] INFO  umbraco.content - Save Xml to file...
 2019-10-28 10:39:48,314 [P4036/D2/T69] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 10:40:04,927 [P4036/D2/T51] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:40:07,969 [P4036/D2/T58] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:40:12,777 [P4036/D2/T58] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:40:17,232 [P4036/D2/T68] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:41:37,712 [P4036/D2/T33] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:41:45,000 [P4036/D2/T68] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:43:15,234 [P4036/D2/T57] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Sverige' with Id '1071' has been unpublished.
 2019-10-28 10:43:16,070 [P4036/D2/T57] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'EcUtbildning' with Id '1072' has been unpublished.
 2019-10-28 10:43:22,808 [P4036/D2/T55] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Denmark' with Id '1073' has been unpublished.
 2019-10-28 10:43:24,605 [P4036/D2/T64] INFO  umbraco.content - Save Xml to file...
 2019-10-28 10:43:24,613 [P4036/D2/T64] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 10:43:29,690 [P4036/D2/T57] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'France' with Id '1074' has been unpublished.
 2019-10-28 10:43:29,854 [P4036/D2/T64] INFO  umbraco.content - Save Xml to file...
 2019-10-28 10:43:29,870 [P4036/D2/T64] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 10:43:36,453 [P4036/D2/T64] INFO  umbraco.content - Save Xml to file...
 2019-10-28 10:43:36,460 [P4036/D2/T64] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 10:43:51,580 [P4036/D2/T32] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 10:44:11,666 [P4036/D2/T53] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Sweden' with Id '0' has been published.
 2019-10-28 10:44:17,765 [P4036/D2/T64] INFO  umbraco.content - Save Xml to file...
 2019-10-28 10:44:17,773 [P4036/D2/T64] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 10:44:46,714 [P4036/D2/T49] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:45:30,201 [P4036/D2/T49] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-10-28 10:45:48,159 [P4036/D2/T23] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-10-28 10:48:11,884 [P4036/D2/T17] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-10-28 10:48:12,785 [P4036/D2/T17] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-10-28 10:48:55,599 [P4036/D2/T62] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 10:49:01,615 [P4036/D2/T58] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 10:53:59,620 [P4036/D2/T14] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 10:57:44,761 [P4036/D2/T53] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field startNode
 2019-10-28 10:57:44,761 [P4036/D2/T53] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field filter
 2019-10-28 10:57:44,761 [P4036/D2/T53] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field minNumber
 2019-10-28 10:57:44,761 [P4036/D2/T53] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxNumber
 2019-10-28 10:59:03,639 [P4036/D2/T51] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:03:47,699 [P4036/D2/T14] INFO  umbraco.content - Save Xml to file...
 2019-10-28 11:03:47,710 [P4036/D2/T14] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 11:04:07,651 [P4036/D2/T39] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:05:58,754 [P4036/D2/T14] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:06:31,137 [P4036/D2/T14] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:07:31,976 [P4036/D2/T49] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:08:41,224 [P4036/D2/T68] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:09:05,786 [P4036/D2/T40] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:09:11,680 [P4036/D2/T48] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:09:50,600 [P4036/D2/T68] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-10-28 11:09:51,443 [P4036/D2/T68] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field maxChars
 2019-10-28 11:10:04,729 [P4036/D2/T40] INFO  umbraco.content - Loading content from database...
 2019-10-28 11:10:09,496 [P4036/D2/T9] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:10:09,514 [P4036/D2/T36] INFO  umbraco.content - Save Xml to file...
 2019-10-28 11:10:09,522 [P4036/D2/T36] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 11:10:18,579 [P4036/D2/T13] INFO  umbraco.content - Loading content from database...
 2019-10-28 11:10:23,766 [P4036/D2/T20] INFO  umbraco.content - Save Xml to file...
 2019-10-28 11:10:23,773 [P4036/D2/T20] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 11:11:26,110 [P4036/D2/T20] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-10-28 11:11:26,110 [P4036/D2/T20] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-10-28 11:11:26,110 [P4036/D2/T20] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Deploy.IServiceConnector
 2019-10-28 11:11:26,120 [P4036/D2/T20] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Deploy.IServiceConnector (took 9ms)
 2019-10-28 11:11:39,196 [P4036/D2/T19] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:11:40,879 [P4036/D2/T51] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:13:04,134 [P4036/D2/T63] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:14:15,691 [P4036/D2/T44] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:14:45,804 [P4036/D2/T36] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:16:28,614 [P4036/D2/T21] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:19:19,708 [P4036/D2/T42] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:20:48,524 [P4036/D2/T59] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:23:42,508 [P4036/D2/T6] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:24:11,132 [P4036/D2/T20] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:24:23,726 [P4036/D2/T45] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:25:03,984 [P4036/D2/T25] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:28:23,450 [P4036/D2/T39] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:29:27,755 [P4036/D2/T17] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:29:38,721 [P4036/D2/T42] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:30:53,119 [P4036/D2/T32] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:31:08,584 [P4036/D2/T71] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:31:18,982 [P4036/D2/T32] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:31:39,816 [P4036/D2/T56] WARN  Umbraco.Web.Models.Mapping.PreValueDisplayResolver - Could not find persisted pre-value for field tabName
 2019-10-28 11:32:38,163 [P4036/D2/T48] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Human Resource' with Id '0' has been published.
 2019-10-28 11:32:45,937 [P4036/D2/T13] INFO  umbraco.content - Save Xml to file...
 2019-10-28 11:32:45,945 [P4036/D2/T13] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 11:33:23,709 [P4036/D2/T51] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Joakim Persson' with Id '0' has been published.
 2019-10-28 11:33:29,749 [P4036/D2/T32] INFO  umbraco.content - Save Xml to file...
 2019-10-28 11:33:29,757 [P4036/D2/T32] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 11:34:31,770 [P4036/D2/T33] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:38:35,353 [P4036/D2/T32] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'John Doe' with Id '0' has been published.
 2019-10-28 11:38:41,654 [P4036/D2/T14] INFO  umbraco.content - Save Xml to file...
 2019-10-28 11:38:41,662 [P4036/D2/T14] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 11:39:35,788 [P4036/D2/T54] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:44:39,813 [P4036/D2/T28] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:49:25,913 [P4036/D2/T11] INFO  Umbraco.Core.Logging.OwinLogger - Event Id: 0, state: User logged will be logged out due to timeout: joakiimm@hotmail.com, IP Address: ::1
 2019-10-28 11:49:43,835 [P4036/D2/T81] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:54:47,858 [P4036/D2/T113] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 11:59:51,874 [P4036/D2/T131] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 12:04:55,892 [P4036/D2/T140] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 12:09:32,337 [P4036/D2/T152] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username joakiimm@hotmail.com from IP address ::1
 2019-10-28 12:09:32,338 [P4036/D2/T152] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: joakiimm@hotmail.com logged in from IP address ::1
 2019-10-28 12:09:59,909 [P4036/D2/T146] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 12:11:18,703 [P4036/D2/T148] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Accounting' with Id '0' has been published.
 2019-10-28 12:11:24,768 [P4036/D2/T135] INFO  umbraco.content - Save Xml to file...
 2019-10-28 12:11:24,778 [P4036/D2/T135] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 12:11:55,195 [P4036/D2/T152] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Jane Doe' with Id '0' has been published.
 2019-10-28 12:12:01,407 [P4036/D2/T138] INFO  umbraco.content - Save Xml to file...
 2019-10-28 12:12:01,416 [P4036/D2/T138] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 12:12:26,535 [P4036/D2/T144] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Janne Doe' with Id '0' has been published.
 2019-10-28 12:12:32,846 [P4036/D2/T138] INFO  umbraco.content - Save Xml to file...
 2019-10-28 12:12:32,854 [P4036/D2/T138] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 12:13:09,113 [P4036/D2/T152] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Pölse Marketing' with Id '0' has been published.
 2019-10-28 12:13:15,041 [P4036/D2/T152] INFO  umbraco.content - Save Xml to file...
 2019-10-28 12:13:15,050 [P4036/D2/T152] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 12:13:49,373 [P4036/D2/T123] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Gösta Doe' with Id '0' has been published.
 2019-10-28 12:13:55,617 [P4036/D2/T135] INFO  umbraco.content - Save Xml to file...
 2019-10-28 12:13:55,625 [P4036/D2/T135] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 12:14:35,750 [P4036/D2/T137] INFO  umbraco.content - Save Xml to file...
 2019-10-28 12:14:35,757 [P4036/D2/T137] INFO  umbraco.content - Saved Xml to file.
 2019-10-28 12:15:03,923 [P4036/D2/T131] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2019-10-28 12:20:07,940 [P4036/D2/T115] ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost/umbraco").
System.Net.Http.HttpRequestException: Ett fel uppstod när begäran skickades. ---> System.Net.WebException: Det går inte att ansluta till fjärrservern ---> System.Net.Sockets.SocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det 127.0.0.1:80
   vid System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   vid System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   vid System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Slut på stackspårning för interna undantag ---
   vid System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   vid System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Slut på stackspårning för interna undantag ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
